### Libraries and Configuration

In [1]:
import pandas as pd

### 1. Reading a .csv from a URL

https://football-data.co.uk/data.php

In [2]:
df_premiere26 = pd.read_csv("https://football-data.co.uk/mmz4281/2526/E0.csv")

In [3]:
df_premiere26.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92

### 2. Renaming the columns

In [4]:
columns = {
    "FTHG": "home_goals",
    "FTAG": "away_goals"
}

df_premiere26 = df_premiere26.rename(columns=columns)

In [5]:
df_premiere26.head()

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92

### 3. Reading multiple URLs

In [6]:
# Link: root + season + league

"https://football-data.co.uk/mmz4281/" + "2526" + "/" + "E0" + ".csv"

'https://football-data.co.uk/mmz4281/2526/E0.csv'

In [7]:
root = "https://football-data.co.uk/mmz4281/"

### 3.1. Multiple leagues

In [8]:
leagues = ["E0", "E1", "E2", "E3", "EC"] # from site
dfs = []

for league in leagues:
    df = pd.read_csv(root + "2526" + "/" + league + ".csv")
    dfs.append(df)

In [9]:
len(dfs)

5

In [10]:
dfs[4].head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,EC,09/08/2025,15:00,Altrincham,Aldershot,3,2,H,2,0,...,1.90,1.90,1.92,1.93,1.90,1.90,1.86,1.84,2.00,1.99
1,EC,09/08/2025,15:00,Boreham Wood,Rochdale,0,2,A,0,0,...,2.00,1.80,2.05,1.82,2.02,1.80,1.96,1.75,2.06,1.89
2,EC,09/08/2025,15:00,Brackley Town,Eastleigh,1,0,H,1,0,...,2.00,1.80,2.14,1.72,2.03,1.80,1.96,1.75,2.06,1.84
3,EC,09/08/2025,15:00,Braintree Town,Halifax,3,0,H,2,0,...,1.93,1.88,1.97,1.88,1.93,1.88,1.88,1.82,1.97,1.98
4,EC,09/08/2025,15:00,Gateshead,Southend,0,3,A,0,1,...,1.83,1.98,1.67,2.19,1.83,2.04,1.75,1.96,1.84,2.12

### 3.2. Multiple seasons

In [11]:
leagues = ["E0", "E1", "E2"] # from site
dfs = []

for league in leagues:
    for season in range(20,26):
        df = pd.read_csv(root + str(season) + str(season+1) + "/" + league + ".csv")
        df["season"] = str(season)

        dfs.append(df)

In [12]:
# 3 leagues x 6 seasons

len(dfs)

18

In [13]:
dfs[17].head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA,season
0,E2,01/08/2025,20:00,Luton,AFC Wimbledon,1,0,H,0,0,...,1.93,1.93,1.95,1.98,1.93,1.91,1.82,1.94,2.01,25
1,E2,02/08/2025,12:30,Cardiff,Peterboro,2,1,H,0,1,...,2.00,1.87,2.03,1.90,2.00,1.85,1.88,1.93,2.04,25
2,E2,02/08/2025,15:00,Blackpool,Stevenage,2,3,A,1,2,...,1.93,1.94,1.94,1.94,1.93,1.84,1.87,1.94,2.04,25
3,E2,02/08/2025,15:00,Bradford,Wycombe,2,1,H,2,0,...,2.08,1.90,1.99,1.77,2.20,1.72,2.02,1.80,2.22,25
4,E2,02/08/2025,15:00,Burton,Mansfield,2,1,H,1,0,...,1.85,1.69,2.26,2.00,1.85,1.93,1.79,2.04,1.93,25

### 4. Organize Data in a Dictionary

In [14]:
dict_countries = {
    "Spanish La Liga": "SP1",
    "Spanish Second Division": "SP2",
    "German Bundesliga": "D1",
    "English Premier League": "E0",
    "English League 1": "E1",
    "English League 2": "E2"
}

In [15]:
dict_countries["Spanish La Liga"]

'SP1'

In [16]:
dict_historical_data = {}

for league in dict_countries:
    dfs = []
    
    for season in range(20,26):
        df = pd.read_csv(root + str(season) + str(season+1) + "/" + dict_countries[league] + ".csv")
        df["season"] = str(season)

        dfs.append(df)

    df_concat = pd.concat(dfs)

    dict_historical_data[league] = df_concat

In [17]:
dict_historical_data.keys()

dict_keys(['Spanish La Liga', 'Spanish Second Division', 'German Bundesliga', 'English Premier League', 'English League 1', 'English League 2'])

In [24]:
dict_historical_data["English Premier League"].head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,E0,12/09/2020,12:30,Fulham,Arsenal,0,3,A,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,12/09/2020,15:00,Crystal Palace,Southampton,1,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,12/09/2020,17:30,Liverpool,Leeds,4,3,H,3,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,12/09/2020,20:00,West Ham,Newcastle,0,2,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,13/09/2020,14:00,West Brom,Leicester,0,3,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN