### 1. Configuration

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("players_20.csv")
df.head()

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3

### 2. Core Concepts

loc()  -> we have to specify rows and columns based on their index/row and columns labels. Write the name of the index or columns to get the data.

iloc() -> we have to specify rows and columns by their inter positions values.

### 3. Configing the df

In [3]:
df = df.set_index("short_name")

In [4]:
df.head()

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
L. Messi,158023,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
Cristiano Ronaldo,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
Neymar Jr,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
J. Oblak,200389,https://sofifa.com/player/200389/jan-oblak/20/...,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E. Hazard,183277,https://sofifa.com/player/183277/eden-hazard/2...,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3

In [5]:
columns = ["long_name", "age", "dob", "height_cm", "weight_kg", "nationality", "club"]
df = df[columns]
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

### 4. Selecting with a single value

loc[row_label, column_label]

In [6]:
df.loc["L. Messi"]

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

In [7]:
df.loc["L. Messi", "height_cm"]

170

In [8]:
df.loc["Cristiano Ronaldo", "weight_kg"]

83

In [9]:
df.loc[:,"height_cm"]

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [10]:
df.loc["L. Messi", :] # the : is optional in this case

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

### 5. Selecting with a multiple values

In [11]:
players = ["L. Messi", "Cristiano Ronaldo"]
df.loc[players]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [12]:
df.loc[players, "height_cm"]

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [13]:
columns = ["height_cm", "weight_kg"]
df.loc["L. Messi", columns]

height_cm    170
weight_kg     72
Name: L. Messi, dtype: object

In [14]:
df.loc[players, columns]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

### 6. Selecting a range of data with a slice

start:stop:step -> both, start and stop elements are included

In [15]:
players = ["L. Messi", "Cristiano Ronaldo"]

df.loc[players, "age":"club"]

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus

In [16]:
df.index[:10]

Index(['L. Messi', 'Cristiano Ronaldo', 'Neymar Jr', 'J. Oblak', 'E. Hazard',
       'K. De Bruyne', 'M. ter Stegen', 'V. van Dijk', 'L. Modrić',
       'M. Salah'],
      dtype='object', name='short_name')

In [17]:
df.loc["L. Messi":"M. Salah", "age":"weight_kg"]

                   age         dob  height_cm  weight_kg
short_name
L. Messi            32  1987-06-24        170         72
Cristiano Ronaldo   34  1985-02-05        187         83
Neymar Jr           27  1992-02-05        175         68
J. Oblak            26  1993-01-07        188         87
E. Hazard           28  1991-01-07        175         74
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
L. Modrić           33  1985-09-09        172         66
M. Salah            27  1992-06-15        175         71

### 7. Selecting with conditions

In [18]:
columns = ["age", "dob", "height_cm", "weight_kg"]

# players with height above 180cm

height = 180
df.loc[df["height_cm"] > height, columns]

                   age         dob  height_cm  weight_kg
short_name
Cristiano Ronaldo   34  1985-02-05        187         83
J. Oblak            26  1993-01-07        188         87
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
...                ...         ...        ...        ...
P. Martin           20  1999-01-05        188         84
Shao Shuai          22  1997-03-10        186         79
Zhang Wei           19  2000-05-16        186         75
Wang Haijian        18  2000-08-02        185         74
Pan Ximing          26  1993-01-11        182         78

[9744 rows x 4 columns]

In [19]:
columns = ["age", "dob", "height_cm", "weight_kg"]

# players with height above 180cm and from Brazil

height = 180
nacionality = "Brazil"

df.loc[(df["height_cm"] > height) & (df["nationality"] == nacionality), columns]

                 age         dob  height_cm  weight_kg
short_name
Alisson           26  1992-10-02        191         91
Ederson           25  1993-08-17        188         86
Casemiro          27  1992-02-23        185         84
Thiago Silva      34  1984-09-22        183         82
Marquinhos        25  1994-05-14        183         75
...              ...         ...        ...        ...
Elsinho           28  1991-04-10        192         72
Bruno Bertinato   21  1998-05-31        194         80
Fabio             23  1996-01-13        188         90
Maxwell           24  1995-02-11        182         68
Osman Junior      26  1992-10-29        181         68

[431 rows x 4 columns]

### 8. Set value to one cell

In [36]:
df = pd.read_csv("players_20.csv")
df = df.set_index("short_name")
columns = ["long_name", "age", "dob", "height_cm", "weight_kg", "nationality", "club"]
df = df[columns]
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

In [24]:
df.loc["L. Messi","height_cm"] = 160

In [ ]:
# df.loc["L. Messi"]["height_cm"] = 160 
# This way I have the problem of changing a copy of the df. I need to use df.copy()

In [25]:
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,160,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

### 9. Set value to entire columns

In [26]:
df.loc[:, "height_cm"] = 190
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,190,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,190,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,190,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,190,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,190,74,Belgium,Real Madrid

### 10. Set value to entire row

In [33]:
df.iloc[-1, :] # Last element

long_name                         潘喜明
age                                26
dob                        1993-01-11
height_cm                         182
weight_kg                          78
nationality                  China PR
club           Hebei China Fortune FC
Name: Pan Ximing, dtype: object

In [34]:
df.iloc[-1, :] = np.nan

In [35]:
df.tail()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Shao Shuai,邵帅,22.0,1997-03-10,186.0,79.0,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22.0,1997-01-01,177.0,66.0,China PR,Shanghai SIPG FC
Zhang Wei,张威,19.0,2000-05-16,186.0,75.0,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18.0,2000-08-02,185.0,74.0,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 11. Set values to multiple cells

In [40]:
players = ["L. Messi", "Cristiano Ronaldo"]

df.loc[players, ["height_cm"]] = 175

In [41]:
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,175,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,175,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

### 12. Set value for rows matching a condition

In [46]:
columns = ["age", "dob", "height_cm", "weight_kg"]

filter = df["height_cm"] > 180

df.loc[filter, columns] = 0

df.head(8)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,175,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,175,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,0,0,0,0,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,0,0,0,0,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,0,0,0,0,Germany,FC Barcelona
V. van Dijk,Virgil van Dijk,0,0,0,0,Netherlands,Liverpool

### 13. Drop row

In [66]:
df = pd.read_csv("players_20.csv")
df = df.set_index("short_name")
columns = ["long_name", "age", "dob", "height_cm", "weight_kg", "nationality", "club"]
df = df[columns]
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

In [67]:
df.drop("L. Messi", axis=0)
# axis=0 -> the element is a row or a index
# axis=1 -> the element is a columns

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [68]:
df.drop(index=["L. Messi"])

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [69]:
players = ["L. Messi", "Cristiano Ronaldo"]

df = df.drop(players, axis=0)
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona

### 14. Drop columns

In [70]:
df.drop("long_name", axis=1)
# axis=0 -> the element is a row or a index
# axis=1 -> the element is a columns

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
Neymar Jr,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
...,...,...,...,...,...,...
Shao Shuai,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [71]:
df.drop(columns="long_name")

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
Neymar Jr,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
...,...,...,...,...,...,...
Shao Shuai,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [72]:
df.columns[[-1]]

Index(['club'], dtype='object')

In [73]:
df.drop(columns=df.columns[[-1]])

,long_name,age,dob,height_cm,weight_kg,nationality
short_name,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany
...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR
Zhang Wei,张威,19,2000-05-16,186,75,China PR
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR

In [74]:
columns = ["long_name", "dob"]

df = df.drop(columns=columns)
df.head()

               age  height_cm  weight_kg nationality                 club
short_name
Neymar Jr       27        175         68      Brazil  Paris Saint-Germain
J. Oblak        26        188         87    Slovenia      Atlético Madrid
E. Hazard       28        175         74     Belgium          Real Madrid
K. De Bruyne    28        181         70     Belgium      Manchester City
M. ter Stegen   27        187         85     Germany         FC Barcelona

### 15. sample()

In [75]:
df = pd.read_csv("players_20.csv")
df = df.set_index("short_name")
columns = ["long_name", "age", "dob", "height_cm", "weight_kg", "nationality", "club"]
df = df[columns]
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

In [79]:
df["nationality"].sample(10, random_state=99)

short_name
R. Alvarado               Mexico
Qiao Wei                China PR
E. Paredes                 Chile
K. Stoyanov             Bulgaria
M. Chudý                Slovakia
D. Sundaram                India
R. Gagliardini             Italy
G. Debeljuh              Croatia
Kim Seung Yong    Korea Republic
M. Hansen                Denmark
Name: nationality, dtype: object

In [82]:
df.sample(frac=0.2, random_state=99)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
R. Alvarado,Roberto Alvarado,20,1998-09-07,176,70,Mexico,Cruz Azul
Qiao Wei,Wei Qiao,31,1987-07-20,187,75,China PR,Shenzhen FC
E. Paredes,Esteban Paredes,38,1980-08-01,178,82,Chile,Colo-Colo
K. Stoyanov,Krum Stoyanov,27,1991-08-01,177,71,Bulgaria,Bulgaria
M. Chudý,Martin Chudý,30,1989-04-23,187,90,Slovakia,Górnik Zabrze
...,...,...,...,...,...,...,...
Pedro León,Pedro León Sánchez Gil,32,1986-11-24,183,73,Spain,SD Eibar
M. Sykes,Mark Sykes,21,1997-08-04,182,78,Northern Ireland,Oxford United
Y. Fofana,Yahia Fofana,18,2000-08-21,194,89,France,Le Havre AC
A. Micai,Alessandro Micai,25,1993-07-24,186,77,Italy,US Salernitana 1919
David Bruno,David Dias Resende Bruno,27,1992-02-14,175,64,Portugal,Astra Giurgiu

In [83]:
df.sample(frac=2, replace=True, random_state=99)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
M. Hauptmeijer,Mike Hauptmeijer,22,1997-03-18,191,70,Netherlands,PEC Zwolle
A. Mosquera,Andrés Mosquera,29,1990-02-20,182,80,Colombia,Club León
V. Thill,Vincent Thill,19,2000-02-04,172,58,Luxembourg,US Orléans Loiret Football
D. Bouanga,Denis Bouanga,24,1994-11-11,180,70,Gabon,AS Saint-Étienne
S. Al Selouli,Saad Al Selouli,21,1998-05-25,168,57,Saudi Arabia,Ettifaq FC
...,...,...,...,...,...,...,...
M. Connor,Matthew Connor,22,1997-04-08,192,82,Republic of Ireland,Waterford FC
J. Northcott,Jordan Northcott,17,2002-02-09,162,60,Scotland,St. Johnstone FC
A. Bodzek,Adam Bodzek,33,1985-09-07,184,81,Poland,Fortuna Düsseldorf
J. Adebayo-Smith,Jordan Adebayo-Smith,18,2001-01-11,181,77,United States,Lincoln City
F. Mac Allister,Francis Manuel Mac Allister,23,1995-10-30,176,71,Argentina,Argentinos Juniors

### 16. query()

In [84]:
df = pd.read_csv("players_20.csv")
df = df.set_index("short_name")
columns = ["long_name", "age", "dob", "height_cm", "weight_kg", "nationality", "club"]
df = df[columns]
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

In [85]:
df.query("age > 34")

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Z. Ibrahimović,Zlatan Ibrahimović,37,1981-10-03,195,95,Sweden,LA Galaxy
Pepe,Képler Laveran Lima Ferreira,36,1983-02-26,188,81,Portugal,FC Porto
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
Casillas,Iker Casillas Fernández,38,1981-05-20,185,84,Spain,FC Porto
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria
...,...,...,...,...,...,...,...
N. Hunt,Nicky Hunt,35,1983-09-03,185,86,England,Crewe Alexandra
K. Ogi,荻 晃太,36,1983-05-05,185,76,Japan,Vissel Kobe
J. McCombe,Jamie McCombe,36,1983-01-01,196,79,England,Lincoln City
G. Maley,Gary Maley,36,1982-08-03,188,90,Scotland,Livingston FC
Zhou Ting,周挺,40,1979-02-05,182,73,China PR,Dalian YiFang FC

In [87]:
df[df["age"] > 34]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Z. Ibrahimović,Zlatan Ibrahimović,37,1981-10-03,195,95,Sweden,LA Galaxy
Pepe,Képler Laveran Lima Ferreira,36,1983-02-26,188,81,Portugal,FC Porto
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
Casillas,Iker Casillas Fernández,38,1981-05-20,185,84,Spain,FC Porto
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria
...,...,...,...,...,...,...,...
N. Hunt,Nicky Hunt,35,1983-09-03,185,86,England,Crewe Alexandra
K. Ogi,荻 晃太,36,1983-05-05,185,76,Japan,Vissel Kobe
J. McCombe,Jamie McCombe,36,1983-01-01,196,79,England,Lincoln City
G. Maley,Gary Maley,36,1982-08-03,188,90,Scotland,Livingston FC
Zhou Ting,周挺,40,1979-02-05,182,73,China PR,Dalian YiFang FC

In [95]:
df.query("age > 34 and nationality == 'Brazil'")

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Juiano Mestres,Juan Everton Mestres de Mesquita,35,1984-02-29,181,82,Brazil,Cruzeiro
Charles,Charles Dias De Oliveira,35,1984-04-04,179,76,Brazil,SD Eibar
Naldo,Ronaldo Aparecido Rodrigues,36,1982-09-10,198,91,Brazil,AS Monaco
Everton Andrão,Everton Jorge Andrade Zanon,35,1984-02-29,177,75,Brazil,Fluminense
Dante,Dante Bonfim da Costa Santos,35,1983-10-18,188,85,Brazil,OGC Nice
...,...,...,...,...,...,...,...
Dillson Teixeiro,Dillson Robson Teixeiro Loto,35,1984-02-29,180,74,Brazil,Fortaleza
Carlos Travisso,Carlos Adilson Travisso Rocha,35,1984-02-29,180,75,Brazil,Goiás
Luis Paezinho,Luis Benjamin Paes Soares,35,1984-02-29,182,75,Brazil,Santos
Fabiem Jardim,Fabiem Kel Jardim Ramos,35,1984-02-29,182,78,Brazil,Fortaleza
Sander Asevedo,Sander Luan Asevedo Cirino,35,1984-02-29,187,80,Brazil,Fortaleza

In [99]:
filter = (df["age"] > 34) & (df["nationality"] == "Brazil")
df[filter]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Juiano Mestres,Juan Everton Mestres de Mesquita,35,1984-02-29,181,82,Brazil,Cruzeiro
Charles,Charles Dias De Oliveira,35,1984-04-04,179,76,Brazil,SD Eibar
Naldo,Ronaldo Aparecido Rodrigues,36,1982-09-10,198,91,Brazil,AS Monaco
Everton Andrão,Everton Jorge Andrade Zanon,35,1984-02-29,177,75,Brazil,Fluminense
Dante,Dante Bonfim da Costa Santos,35,1983-10-18,188,85,Brazil,OGC Nice
...,...,...,...,...,...,...,...
Dillson Teixeiro,Dillson Robson Teixeiro Loto,35,1984-02-29,180,74,Brazil,Fortaleza
Carlos Travisso,Carlos Adilson Travisso Rocha,35,1984-02-29,180,75,Brazil,Goiás
Luis Paezinho,Luis Benjamin Paes Soares,35,1984-02-29,182,75,Brazil,Santos
Fabiem Jardim,Fabiem Kel Jardim Ramos,35,1984-02-29,182,78,Brazil,Fortaleza
Sander Asevedo,Sander Luan Asevedo Cirino,35,1984-02-29,187,80,Brazil,Fortaleza

In [100]:
df.query("not (age > 34)")

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [106]:
df[~(df["age"] > 34)]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [108]:
df.query("height_cm / 100 > 1.8")

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
...,...,...,...,...,...,...,...
P. Martin,Paul Martin,20,1999-01-05,188,84,Republic of Ireland,Waterford FC
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [109]:
df[df["height_cm"]/100 > 1.8]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
...,...,...,...,...,...,...,...
P. Martin,Paul Martin,20,1999-01-05,188,84,Republic of Ireland,Waterford FC
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [110]:
df.dtypes

long_name      object
age             int64
dob            object
height_cm       int64
weight_kg       int64
nationality    object
club           object
dtype: object

In [115]:
df["dob"] = df["dob"].astype("datetime64[s]")

In [116]:
df["dob"].dt.year

short_name
L. Messi             1987
Cristiano Ronaldo    1985
Neymar Jr            1992
J. Oblak             1993
E. Hazard            1991
                     ...
Shao Shuai           1997
Xiao Mingjie         1997
Zhang Wei            2000
Wang Haijian         2000
Pan Ximing           1993
Name: dob, Length: 18278, dtype: int32

In [118]:
df.query("dob.dt.year > 2000")

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Rodrygo,Rodrygo Silva de Goes,18,2001-01-09,174,64,Brazil,Real Madrid
Kangin Lee,이강인 Kangin Lee,18,2001-02-19,173,61,Korea Republic,Valencia CF
T. Almada,Thiago Almada,18,2001-04-26,171,62,Argentina,Vélez Sarsfield
Y. Verschaeren,Yari Verschaeren,17,2001-07-12,172,63,Belgium,RSC Anderlecht
W. Saliba,William Saliba,18,2001-03-24,192,85,France,AS Saint-Étienne
...,...,...,...,...,...,...,...
H. Kyprianou,Hector Kyprianou,18,2001-05-27,182,74,Cyprus,Leyton Orient
T. Klysner,Tobias Klysner,17,2001-07-03,170,69,Denmark,Randers FC
E. Jääskeläinen,Emil Jääskeläinen,18,2001-03-16,183,66,Finland,Blackpool
L. Collins,Lewis Collins,18,2001-05-09,178,67,Wales,Newport County
H. Sveijer,Hannes Sveijer,17,2002-04-28,185,71,Sweden,IK Sirius

In [119]:
df[df["dob"].dt.year > 2000]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Rodrygo,Rodrygo Silva de Goes,18,2001-01-09,174,64,Brazil,Real Madrid
Kangin Lee,이강인 Kangin Lee,18,2001-02-19,173,61,Korea Republic,Valencia CF
T. Almada,Thiago Almada,18,2001-04-26,171,62,Argentina,Vélez Sarsfield
Y. Verschaeren,Yari Verschaeren,17,2001-07-12,172,63,Belgium,RSC Anderlecht
W. Saliba,William Saliba,18,2001-03-24,192,85,France,AS Saint-Étienne
...,...,...,...,...,...,...,...
H. Kyprianou,Hector Kyprianou,18,2001-05-27,182,74,Cyprus,Leyton Orient
T. Klysner,Tobias Klysner,17,2001-07-03,170,69,Denmark,Randers FC
E. Jääskeläinen,Emil Jääskeläinen,18,2001-03-16,183,66,Finland,Blackpool
L. Collins,Lewis Collins,18,2001-05-09,178,67,Wales,Newport County
H. Sveijer,Hannes Sveijer,17,2002-04-28,185,71,Sweden,IK Sirius

### 17. apply()

In [120]:
df["age"].apply(np.sqrt)

short_name
L. Messi             5.656854
Cristiano Ronaldo    5.830952
Neymar Jr            5.196152
J. Oblak             5.099020
E. Hazard            5.291503
                       ...
Shao Shuai           4.690416
Xiao Mingjie         4.690416
Zhang Wei            4.358899
Wang Haijian         4.242641
Pan Ximing           5.099020
Name: age, Length: 18278, dtype: float64

In [121]:
def calculate_bmi(row):
    row["height_cm"] = row["height_cm"] / 100
    bmi = row["weight_kg"] / row["height_cm"]**2
    
    return bmi

In [123]:
df.apply(calculate_bmi, axis=1)

short_name
L. Messi             24.913495
Cristiano Ronaldo    23.735308
Neymar Jr            22.204082
J. Oblak             24.615211
E. Hazard            24.163265
                       ...
Shao Shuai           22.835010
Xiao Mingjie         21.066743
Zhang Wei            21.678807
Wang Haijian         21.621622
Pan Ximing           23.547881
Length: 18278, dtype: float64

### 18. Lambda function

In [124]:
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

In [125]:
def sum_values(a, b):
    x = a + b

    return x

In [126]:
sum_values(2,3)

5

In [127]:
sum_values_lambda = lambda a, b:a + b

In [128]:
sum_values_lambda(2,3)

5

### 19. Apply + Lambda Function

In [129]:
df["height_cm"].apply(lambda x:x/100)

short_name
L. Messi             1.70
Cristiano Ronaldo    1.87
Neymar Jr            1.75
J. Oblak             1.88
E. Hazard            1.75
                     ...
Shao Shuai           1.86
Xiao Mingjie         1.77
Zhang Wei            1.86
Wang Haijian         1.85
Pan Ximing           1.82
Name: height_cm, Length: 18278, dtype: float64

In [130]:
df["height_cm"]/100

short_name
L. Messi             1.70
Cristiano Ronaldo    1.87
Neymar Jr            1.75
J. Oblak             1.88
E. Hazard            1.75
                     ...
Shao Shuai           1.86
Xiao Mingjie         1.77
Zhang Wei            1.86
Wang Haijian         1.85
Pan Ximing           1.82
Name: height_cm, Length: 18278, dtype: float64

In [ ]:
df["long_name"].apply(lambda x: x.upper())

short_name
L. Messi                  LIONEL ANDRÉS MESSI CUCCITTINI
Cristiano Ronaldo    CRISTIANO RONALDO DOS SANTOS AVEIRO
Neymar Jr                  NEYMAR DA SILVA SANTOS JUNIOR
J. Oblak                                       JAN OBLAK
E. Hazard                                    EDEN HAZARD
                                    ...
Shao Shuai                                            邵帅
Xiao Mingjie                                MINGJIE XIAO
Zhang Wei                                             张威
Wang Haijian                                         汪海健
Pan Ximing                                           潘喜明
Name: long_name, Length: 18278, dtype: object

In [135]:
df["long_name"].str.upper()

short_name
L. Messi                  LIONEL ANDRÉS MESSI CUCCITTINI
Cristiano Ronaldo    CRISTIANO RONALDO DOS SANTOS AVEIRO
Neymar Jr                  NEYMAR DA SILVA SANTOS JUNIOR
J. Oblak                                       JAN OBLAK
E. Hazard                                    EDEN HAZARD
                                    ...
Shao Shuai                                            邵帅
Xiao Mingjie                                MINGJIE XIAO
Zhang Wei                                             张威
Wang Haijian                                         汪海健
Pan Ximing                                           潘喜明
Name: long_name, Length: 18278, dtype: object

In [138]:
df["dob"].apply(lambda x: x.year)

short_name
L. Messi             1987
Cristiano Ronaldo    1985
Neymar Jr            1992
J. Oblak             1993
E. Hazard            1991
                     ...
Shao Shuai           1997
Xiao Mingjie         1997
Zhang Wei            2000
Wang Haijian         2000
Pan Ximing           1993
Name: dob, Length: 18278, dtype: int64

In [139]:
df["dob"].dt.year

short_name
L. Messi             1987
Cristiano Ronaldo    1985
Neymar Jr            1992
J. Oblak             1993
E. Hazard            1991
                     ...
Shao Shuai           1997
Xiao Mingjie         1997
Zhang Wei            2000
Wang Haijian         2000
Pan Ximing           1993
Name: dob, Length: 18278, dtype: int32

In [146]:
df.apply(lambda x: x["weight_kg"] / (x["height_cm"]/100)**2, axis=1)

short_name
L. Messi             24.913495
Cristiano Ronaldo    23.735308
Neymar Jr            22.204082
J. Oblak             24.615211
E. Hazard            24.163265
                       ...
Shao Shuai           22.835010
Xiao Mingjie         21.066743
Zhang Wei            21.678807
Wang Haijian         21.621622
Pan Ximing           23.547881
Length: 18278, dtype: float64

### 20. copy()

#### 20.1. deep = True

by defalt -> moditications to the data and indices of the df are not reflected in the copy

In [147]:
df_copy = df.copy()
df_copy.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

In [149]:
df.loc["L. Messi","height_cm"] = 180

In [151]:
df.loc["L. Messi", "height_cm"]

180

In [152]:
df_copy.loc["L. Messi", "height_cm"]

170

#### 20.2. deep = False

by defalt -> moditications to the data and indices of the df are reflected in the copy

In [167]:
df_copy = df.copy(deep=False)
df_copy.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,180,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

In [168]:
df.loc["L. Messi","weight_kg"] = 62

In [169]:
df.loc["L. Messi", "weight_kg"]

62

In [170]:
df_copy.loc["L. Messi", "weight_kg"]

62

#### 20.3. Simple assignment

In [171]:
df_new_copy = df

In [174]:
df.loc["Cristiano Ronaldo", "nationality"] = "Brazil"

In [177]:
df.loc["Cristiano Ronaldo", "nationality"]

'Brazil'

In [178]:
df_new_copy.loc["Cristiano Ronaldo", "nationality"]

'Brazil'

In [179]:
df_corret = df.copy()