### 1. Configuration

In [1]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_csv("players_20.csv")
df = df.set_index("short_name")
df.head()

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
L. Messi,158023,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
Cristiano Ronaldo,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
Neymar Jr,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
J. Oblak,200389,https://sofifa.com/player/200389/jan-oblak/20/...,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E. Hazard,183277,https://sofifa.com/player/183277/eden-hazard/2...,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3

### 2. Selecting with a single value

iloc[row_label, column_label]

In [36]:
columns = ["long_name", "age", "dob", "height_cm", "weight_kg", "nationality", "club"]
df = df[columns]

In [37]:
df.iloc[0]["height_cm"]

170

In [38]:
df.iloc[0,3]

170

In [39]:
df.iloc[1]["weight_kg"]

83

In [40]:
df.iloc[:]["height_cm"]

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [41]:
df.iloc[0, :]

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

### 3. Selecting with a multiple values

In [42]:
players_index = [0, 1]
df.iloc[players_index]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [43]:
df.iloc[players_index]["height_cm"]

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [44]:
columns = [3,4]
df.iloc[0, columns]

height_cm    170
weight_kg     72
Name: L. Messi, dtype: object

In [45]:
df.iloc[0][["height_cm", "weight_kg"]]

height_cm    170
weight_kg     72
Name: L. Messi, dtype: object

In [46]:
df.iloc[players_index][["height_cm", "weight_kg"]]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

In [47]:
df.iloc[players_index, columns]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

### 4. Selecting a range of data with a slice

start:stop:step -> both, start and stop elements are included

In [53]:
players_index = [0, 1]

df.iloc[players_index, 1:]

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus

In [58]:
columns = [1, 2, 3, 4]

df.iloc[0:10, columns]

                   age         dob  height_cm  weight_kg
short_name
L. Messi            32  1987-06-24        170         72
Cristiano Ronaldo   34  1985-02-05        187         83
Neymar Jr           27  1992-02-05        175         68
J. Oblak            26  1993-01-07        188         87
E. Hazard           28  1991-01-07        175         74
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
L. Modrić           33  1985-09-09        172         66
M. Salah            27  1992-06-15        175         71

In [ ]:
df.iloc[0:10, 1:5]

                   age         dob  height_cm  weight_kg
short_name
L. Messi            32  1987-06-24        170         72
Cristiano Ronaldo   34  1985-02-05        187         83
Neymar Jr           27  1992-02-05        175         68
J. Oblak            26  1993-01-07        188         87
E. Hazard           28  1991-01-07        175         74
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
L. Modrić           33  1985-09-09        172         66
M. Salah            27  1992-06-15        175         71

### 5. Selecting with conditions

iloc cannot accept a boolean Series, but only a boolean list. We have to use the list() function to convert a Series into a boolean list

In [64]:
columns = [1, 2, 3, 4]
height = 180

df.iloc[list(df["height_cm"] > 180), columns]

                   age         dob  height_cm  weight_kg
short_name
Cristiano Ronaldo   34  1985-02-05        187         83
J. Oblak            26  1993-01-07        188         87
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
...                ...         ...        ...        ...
P. Martin           20  1999-01-05        188         84
Shao Shuai          22  1997-03-10        186         79
Zhang Wei           19  2000-05-16        186         75
Wang Haijian        18  2000-08-02        185         74
Pan Ximing          26  1993-01-11        182         78

[9744 rows x 4 columns]

In [ ]:
columns = [1, 2, 3, 4]
height = 180
nacionality = "Brazil"

df.iloc[list((df["height_cm"] > height) & (df["nationality"] == nacionality)), columns]

                 age         dob  height_cm  weight_kg
short_name
Alisson           26  1992-10-02        191         91
Ederson           25  1993-08-17        188         86
Casemiro          27  1992-02-23        185         84
Thiago Silva      34  1984-09-22        183         82
Marquinhos        25  1994-05-14        183         75
...              ...         ...        ...        ...
Elsinho           28  1991-04-10        192         72
Bruno Bertinato   21  1998-05-31        194         80
Fabio             23  1996-01-13        188         90
Maxwell           24  1995-02-11        182         68
Osman Junior      26  1992-10-29        181         68

[431 rows x 4 columns]

In [69]:
columns = [1, 2, 3, 4]
height = 180
nacionality = "Brazil"

filter = list(
    (df["height_cm"] > height) & 
    (df["nationality"] == nacionality)
    )

df.iloc[filter, columns]

                 age         dob  height_cm  weight_kg
short_name
Alisson           26  1992-10-02        191         91
Ederson           25  1993-08-17        188         86
Casemiro          27  1992-02-23        185         84
Thiago Silva      34  1984-09-22        183         82
Marquinhos        25  1994-05-14        183         75
...              ...         ...        ...        ...
Elsinho           28  1991-04-10        192         72
Bruno Bertinato   21  1998-05-31        194         80
Fabio             23  1996-01-13        188         90
Maxwell           24  1995-02-11        182         68
Osman Junior      26  1992-10-29        181         68

[431 rows x 4 columns]