### 1. Configuration

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_laptops = pd.read_csv("laptop_price.csv", encoding="latin-1")
df_laptops.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

### 2. Exercises

In [3]:
df_laptops[df_laptops["Company"] != "HP"].head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60
5,6,Acer,Aspire 3,Notebook,15.6,1366x768,AMD A9-Series 9420 3GHz,4GB,500GB HDD,AMD Radeon R5,Windows 10,2.1kg,400.00

In [4]:
df_laptops[df_laptops["Company"] != "HP"].value_counts("Company")

Company
Lenovo       297
Dell         297
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Mediacom       7
Razer          7
Microsoft      6
Vero           4
Xiaomi         4
Chuwi          3
Fujitsu        3
Google         3
LG             3
Huawei         2
Name: count, dtype: int64

In [5]:
df_laptops[df_laptops["Price_euros"] > 2000].head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
6,7,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.2GHz,16GB,256GB Flash Storage,Intel Iris Pro Graphics,Mac OS X,2.04kg,2139.97
12,13,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.8GHz,16GB,256GB SSD,AMD Radeon Pro 555,macOS,1.83kg,2439.97
17,18,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.9GHz,16GB,512GB SSD,AMD Radeon Pro 560,macOS,1.83kg,2858.00
58,59,MSI,GS73VR 7RG,Gaming,17.3,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 2TB HDD,Nvidia GeForce GTX 1070,Windows 10,2.43kg,2449.00

In [6]:
df_laptops[df_laptops["Price_euros"] > 2000]["Price_euros"].min()

2013.1

### 3. Exercise

In [7]:
base_value = 14

df_laptops["Screen_type"] = np.where(df_laptops["Inches"] > base_value, "Big Screen", "Small Screen")

In [8]:
df_laptops.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Screen_type
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Small Screen
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Small Screen
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Big Screen
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Big Screen
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Small Screen

In [9]:
df_laptops.value_counts("Screen_type")

Screen_type
Big Screen      840
Small Screen    463
Name: count, dtype: int64

### 4. Exercise

In [10]:
conditions = [
    (df_laptops["Inches"] > 16),
    (df_laptops["Inches"] > 14),
    (df_laptops["Inches"] > 12),
    (df_laptops["Inches"] <= 12)
]

# If I don't specify the ranges (e.g., greater than 14 and less than or equal to 16),
# it will still work as long as the conditions are ordered correctly.
# In this example, they are ordered from highest to lowest (descending order).
# If I change the order, the result may be incorrect because np.select()
# returns the first matching condition.
# As a good practice, it is better to define explicit ranges:

# conditions = [
#     (df_laptops["Inches"] > 16),
#     (df_laptops["Inches"] > 14) & (df_laptops["Inches"] <= 16),
#     (df_laptops["Inches"] > 12) & (df_laptops["Inches"] <= 14),
#     (df_laptops["Inches"] <= 12)
# ]

values = ["Too Big", "Big", "Small", "Too Small"]

In [11]:
df_laptops["Screen_size"] = np.select(conditions, values)

In [12]:
df_laptops.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Screen_type,Screen_size
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Small Screen,Small
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Small Screen,Small
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Big Screen,Big
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Big Screen,Big
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Small Screen,Small

In [13]:
df_laptops["Screen_size"].value_counts()

Screen_size
Big          674
Small        419
Too Big      166
Too Small     44
Name: count, dtype: int64

### 5. Exercise

In [14]:
df_laptops = pd.read_csv("laptop_price.csv", encoding="latin-1") # reseting df

In [15]:
df_laptops.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [16]:
df_laptops.sort_values(["Company", "Inches"], inplace=True)

In [17]:
df_laptops[~df_laptops.duplicated(["Company"])][["Company", "Inches"]]

        Company  Inches
319        Acer    11.6
1234      Apple    11.6
20         Asus    11.6
421       Chuwi    12.3
455        Dell    11.6
567     Fujitsu    15.6
437      Google    12.3
677          HP    11.6
170      Huawei    13.0
909          LG    14.0
50       Lenovo    10.1
785         MSI    14.0
429    Mediacom    11.6
70    Microsoft    13.5
816       Razer    12.5
430     Samsung    11.6
963     Toshiba    12.5
1120       Vero    13.3
192      Xiaomi    13.3

In [18]:
df_laptops[~df_laptops.duplicated(["Company"], keep="last")][["Company", "Inches"]]

        Company  Inches
1216       Acer    17.3
17        Apple    15.4
1256       Asus    17.3
483       Chuwi    15.6
1243       Dell    17.3
983     Fujitsu    15.6
762      Google    12.3
1136         HP    17.3
214      Huawei    13.0
905          LG    15.6
1217     Lenovo    17.3
177         MSI    18.4
718    Mediacom    14.0
670   Microsoft    13.5
830       Razer    17.3
593     Samsung    15.6
1042    Toshiba    15.6
1041       Vero    14.0
514      Xiaomi    15.6