### 1. Configuration

In [1]:
import pandas as pd
import numpy as np

In [35]:
df_movies = pd.read_csv("IMDb movies.csv", low_memory=False)

movie_columns = [
    "imdb_title_id", 
    "title", 
    "year", 
    "genre", 
    "country"
    ]

df_movies = df_movies[movie_columns]
df_movies.head()

,imdb_title_id,title,year,genre,country
0,tt0000009,Miss Jerry,1894,Romance,USA
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,Cleopatra,1912,"Drama, History",USA
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy

In [36]:
df_ratings = pd.read_csv("IMDb ratings.csv", low_memory=False)

rating_columns = [
    "imdb_title_id", 
    "total_votes", 
    "mean_vote"
    ]

df_ratings = df_ratings[rating_columns]
df_ratings.head()

  imdb_title_id  total_votes  mean_vote
0     tt0000009          154        5.9
1     tt0000574          589        6.3
2     tt0001892          188        6.0
3     tt0002101          446        5.3
4     tt0002130         2237        6.9

### 2.  Concatenate

#### 2.1. Concatenate -> Vertically (axis=0)

pd.concat([df1, df2])

In [15]:
df1 = pd.DataFrame({
    "id": ["A", "B", "C", "D"],
    "age": [30, 23, 25, 22]
})

df2 = pd.DataFrame({
    "id": ["E", "F", "G", "H"],
    "age": [40, 21, 19, 24]
})

In [16]:
pd.concat([df1, df2], axis=0, ignore_index=True)

  id  age
0  A   30
1  B   23
2  C   25
3  D   22
4  E   40
5  F   21
6  G   19
7  H   24

#### 2.1.1. Exercise

In [22]:
df_sample = df_movies.sample(frac=0.5)

In [26]:
print("Shape df_movies:", df_movies.shape)
print("Shape df_sample:", df_sample.shape)

Shape df_movies: (85855, 5)
Shape df_sample: (42928, 5)

In [25]:
pd.concat([df_sample, df_movies], axis=0, ignore_index=True).shape

(128783, 5)

#### 2.2. Concatenate -> Horizontally (axis=1)

pd.concat([df1, df2], axis=1)

In [27]:
df3 = pd.DataFrame({
    "job": ["Doctor", "Statistician", "Accountant", "Developer"]
})

In [29]:
pd.concat([df1, df3], axis=1)

  id  age           job
0  A   30        Doctor
1  B   23  Statistician
2  C   25    Accountant
3  D   22     Developer

#### 2.2.1. Exercise

In [30]:
print("Shape df_movies:", df_movies.shape)
print("Shape df_ratings:", df_ratings.shape)

Shape df_movies: (85855, 5)
Shape df_ratings: (85855, 3)

In [37]:
df_movies = df_movies.set_index("imdb_title_id")
df_ratings = df_ratings.set_index("imdb_title_id")

In [ ]:
df_concat = pd.concat([df_movies, df_ratings], axis=1, sort=True)

In [39]:
df_concat.head()

,title,year,genre,country,total_votes,mean_vote
imdb_title_id,,,,,,
tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9

In [40]:
print("Shape df_concat:", df_concat.shape)

Shape df_concat: (85855, 6)