## 1. Basics

### 1.1 General

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

In [3]:
columns = ["i", "j", "k"]
indexes = ["a", "b", "c"]

df = pd.DataFrame(data, columns=columns, index=indexes)

In [4]:
df

   i  j  k
a  1  0  0
b  0  1  0
c  0  0  1

In [5]:
df = [
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 6]
    ]

columns = ["A", "B", "C"]

pd.DataFrame(df, columns=columns)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  6

### 1.2 DataFrame from a dictionary

In [6]:
states = ["São Paulo", "Paraná", "Maranhão", "Mato Grosso"]
population = [46649132, 11890517, 7018211, 3836399]

In [7]:
dict_states = {"States":states, "Population":population}

In [8]:
df_pop = pd.DataFrame(dict_states)

In [9]:
df_pop

        States  Population
0    São Paulo    46649132
1       Paraná    11890517
2     Maranhão     7018211
3  Mato Grosso     3836399

### 1.3 DataFrame from a csv

In [10]:
df_exams = pd.read_csv("StudentsPerformance.csv")

In [11]:
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [12]:
df_exams.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [13]:
df_exams.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [14]:
df_exams.shape

(1000, 8)

In [15]:
# n = 1000
# pd.set_option("display.max_rows", 1000)

## 2. Methods

In [16]:
df_exams.index

RangeIndex(start=0, stop=1000, step=1)

In [17]:
df_exams.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [18]:
df_exams.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [19]:
df_exams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [20]:
df_exams.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

 ## 3. Functions

In [21]:
len(df_exams)

1000

In [22]:
max(df_exams.index)

999

In [23]:
min(df_exams.index)

0

In [24]:
type(df_exams)

pandas.core.frame.DataFrame

In [25]:
round(df_exams, 2).head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

## 4. Selecting one column

### 4.1. Syntax 1

In [26]:
## Prefered way

df_exams["gender"]

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [27]:
type(df_exams["gender"])

pandas.core.series.Series

In [28]:
df_exams["gender"].index
df_exams["gender"].head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

### 4.2. Syntax 2

In [29]:
df_exams.gender.head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

In [30]:
# df_exams.math score

In [31]:
df_exams["math score"].head()

0    72
1    69
2    90
3    47
4    76
Name: math score, dtype: int64

## 5. Selecting two or more columns

In [32]:
df_exams[["gender", "math score"]].head()

   gender  math score
0  female          72
1  female          69
2  female          90
3    male          47
4    male          76

In [33]:
type(df_exams[["gender"]])

pandas.core.frame.DataFrame

In [34]:
type(df_exams[["gender", "math score"]])

## If I use [] to select one column -> series
## If I use [[]] to select one column -> dataFrame

pandas.core.frame.DataFrame

In [35]:
columns = ["gender", "writing score", "math score", "reading score"] ## the order of the colums I define just to puting in my desire order
df_exams[columns].head()

   gender  writing score  math score  reading score
0  female             74          72             72
1  female             88          69             90
2  female             93          90             95
3    male             44          47             57
4    male             75          76             78

## 6. Adding a new column

### 6.1. Adding a new column with a scalar value

In [36]:
df_exams["language score"] = 70
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70

### 6.2. Adding a new column with an array

In [37]:
import numpy as np

In [38]:
language_score = np.arange(0, 1000)
len(language_score)

1000

In [39]:
df_exams["language score"] = language_score
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4

In [40]:
language_score = np.random.randint(0, 101, size=1000)
len(language_score)

1000

In [41]:
df_exams["language score"] = language_score
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,44
1,female,group C,some college,standard,completed,69,90,88,53
2,female,group B,master's degree,standard,none,90,95,93,42
3,male,group A,associate's degree,free/reduced,none,47,57,44,81
4,male,group C,some college,standard,none,76,78,75,88

In [42]:
language_score = np.random.uniform(0, 100, size=1000)
len(language_score)

1000

In [43]:
df_exams["language score"] = language_score.round(2)
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,82.15
1,female,group C,some college,standard,completed,69,90,88,0.88
2,female,group B,master's degree,standard,none,90,95,93,21.79
3,male,group A,associate's degree,free/reduced,none,47,57,44,20.33
4,male,group C,some college,standard,none,76,78,75,41.65

### 6.3. Adding a new column with assign()

When use assing()

- Add multiple columns in a single line of code
- When you need to overwrite the values on an existing column (best practice)

In [44]:
score1 = np.random.randint(1, 101, size=1000)
score2 = np.random.randint(1, 101, size=1000)

In [45]:
series1 = pd.Series(score1, index=np.arange(0, 1000))
series2 = pd.Series(score2, index=np.arange(0, 1000))

In [46]:
type(score1)

numpy.ndarray

In [47]:
type(series1)

pandas.core.series.Series

In [48]:
df_exams = df_exams.assign(score_A=series1, score_B=series2)

In [49]:
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_A,score_B
0,female,group B,bachelor's degree,standard,none,72,72,74,82.15,90,94
1,female,group C,some college,standard,completed,69,90,88,0.88,37,68
2,female,group B,master's degree,standard,none,90,95,93,21.79,8,81
3,male,group A,associate's degree,free/reduced,none,47,57,44,20.33,12,29
4,male,group C,some college,standard,none,76,78,75,41.65,84,92

### 6.4. Adding a new column with intert()

In [50]:
df_exams.insert(1, "test", series1)
df_exams.head()

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_A,score_B
0,female,90,group B,bachelor's degree,standard,none,72,72,74,82.15,90,94
1,female,37,group C,some college,standard,completed,69,90,88,0.88,37,68
2,female,8,group B,master's degree,standard,none,90,95,93,21.79,8,81
3,male,12,group A,associate's degree,free/reduced,none,47,57,44,20.33,12,29
4,male,84,group C,some college,standard,none,76,78,75,41.65,84,92

## 7. Math Operations

### 7.1. Operations in columns

In [63]:
from IPython.display import display

display(df_exams[["math score"]].sum())
display(df_exams[["math score"]].count())
display(df_exams[["math score"]].mean())
display(df_exams[["math score"]].std())
display(df_exams[["math score"]].max())
display(df_exams[["math score"]].min())

math score    66089
dtype: int64

math score    1000
dtype: int64

math score    66.089
dtype: float64

math score    15.16308
dtype: float64

math score    100
dtype: int64

math score    0
dtype: int64

In [65]:
df_exams[["math score"]].describe()

       math score
count  1000.00000
mean     66.08900
std      15.16308
min       0.00000
25%      57.00000
50%      66.00000
75%      77.00000
max     100.00000

### 7.2. Operations in rows

In [67]:
df_exams["math score"] + df_exams["reading score"] + df_exams["writing score"]

0      218
1      247
2      278
3      148
4      229
      ...
995    282
996    172
997    195
998    223
999    249
Length: 1000, dtype: int64

In [70]:
df_exams["average score"] = (df_exams["math score"] + df_exams["reading score"] + df_exams["writing score"])/3
df_exams.round(2).head()

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_A,score_B,average score
0,female,90,group B,bachelor's degree,standard,none,72,72,74,82.15,90,94,72.67
1,female,37,group C,some college,standard,completed,69,90,88,0.88,37,68,82.33
2,female,8,group B,master's degree,standard,none,90,95,93,21.79,8,81,92.67
3,male,12,group A,associate's degree,free/reduced,none,47,57,44,20.33,12,29,49.33
4,male,84,group C,some college,standard,none,76,78,75,41.65,84,92,76.33

## 8. Value Counts

In [72]:
len(df_exams["gender"])

1000

In [73]:
df_exams["gender"].count()

1000

In [75]:
df_exams["gender"].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [ ]:
df_exams["gender"].value_counts(normalize=True) # To calculate the percentage of each value

gender
female    0.518
male      0.482
Name: proportion, dtype: float64

In [78]:
df_exams["parental level of education"].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [80]:
df_exams["parental level of education"].value_counts(normalize=True).round(2)

parental level of education
some college          0.23
associate's degree    0.22
high school           0.20
some high school      0.18
bachelor's degree     0.12
master's degree       0.06
Name: proportion, dtype: float64

## 9. Sort a DataFrame

In [83]:
df_exams.sort_values(by="math score")

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_A,score_B,average score
59,female,85,group C,some high school,free/reduced,none,0,17,10,51.58,85,97,9.000000
980,female,40,group B,high school,free/reduced,none,8,24,23,22.23,40,94,18.333333
17,female,43,group B,some high school,free/reduced,none,18,32,28,56.24,43,80,26.000000
787,female,41,group B,some college,standard,none,19,38,32,13.83,41,76,29.666667
145,female,8,group C,some college,free/reduced,none,22,39,33,45.46,8,84,31.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
625,male,6,group D,some college,standard,completed,100,97,99,80.42,6,62,98.666667
623,male,24,group A,some college,standard,completed,100,96,86,23.07,24,39,94.000000
451,female,70,group E,some college,standard,none,100,92,97,10.87,70,75,96.333333
962,female,37,group E,associate's degree,standard,none,100,100,100,49.79,37,94,100.000000
149,male,78,group E,associate's degree,free/reduced,completed,100,100,93,24.75,78,77,97.666667

In [82]:
df_exams.sort_values(by="math score", ascending=False)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_A,score_B,average score
962,female,37,group E,associate's degree,standard,none,100,100,100,49.79,37,94,100.000000
625,male,6,group D,some college,standard,completed,100,97,99,80.42,6,62,98.666667
458,female,15,group E,bachelor's degree,standard,none,100,100,100,85.94,15,53,100.000000
623,male,24,group A,some college,standard,completed,100,96,86,23.07,24,39,94.000000
451,female,70,group E,some college,standard,none,100,92,97,10.87,70,75,96.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,8,group C,some college,free/reduced,none,22,39,33,45.46,8,84,31.333333
787,female,41,group B,some college,standard,none,19,38,32,13.83,41,76,29.666667
17,female,43,group B,some high school,free/reduced,none,18,32,28,56.24,43,80,26.000000
980,female,40,group B,high school,free/reduced,none,8,24,23,22.23,40,94,18.333333
59,female,85,group C,some high school,free/reduced,none,0,17,10,51.58,85,97,9.000000

In [85]:
columns = ["math score", "reading score", "writing score"]
df_exams.sort_values(by=columns, ascending=False)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_A,score_B,average score
458,female,15,group E,bachelor's degree,standard,none,100,100,100,85.94,15,53,100.000000
916,male,33,group E,bachelor's degree,standard,completed,100,100,100,38.13,33,49,100.000000
962,female,37,group E,associate's degree,standard,none,100,100,100,49.79,37,94,100.000000
149,male,78,group E,associate's degree,free/reduced,completed,100,100,93,24.75,78,77,97.666667
625,male,6,group D,some college,standard,completed,100,97,99,80.42,6,62,98.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,8,group C,some college,free/reduced,none,22,39,33,45.46,8,84,31.333333
787,female,41,group B,some college,standard,none,19,38,32,13.83,41,76,29.666667
17,female,43,group B,some high school,free/reduced,none,18,32,28,56.24,43,80,26.000000
980,female,40,group B,high school,free/reduced,none,8,24,23,22.23,40,94,18.333333
59,female,85,group C,some high school,free/reduced,none,0,17,10,51.58,85,97,9.000000

In [ ]:
columns = ["math score", "reading score", "writing score"]
df_exams.sort_values(
    by=columns, 
    ascending=False, 
    inplace=True
    )

df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_A,score_B,average score
458,female,15,group E,bachelor's degree,standard,none,100,100,100,85.94,15,53,100.000000
916,male,33,group E,bachelor's degree,standard,completed,100,100,100,38.13,33,49,100.000000
962,female,37,group E,associate's degree,standard,none,100,100,100,49.79,37,94,100.000000
149,male,78,group E,associate's degree,free/reduced,completed,100,100,93,24.75,78,77,97.666667
625,male,6,group D,some college,standard,completed,100,97,99,80.42,6,62,98.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,8,group C,some college,free/reduced,none,22,39,33,45.46,8,84,31.333333
787,female,41,group B,some college,standard,none,19,38,32,13.83,41,76,29.666667
17,female,43,group B,some high school,free/reduced,none,18,32,28,56.24,43,80,26.000000
980,female,40,group B,high school,free/reduced,none,8,24,23,22.23,40,94,18.333333
59,female,85,group C,some high school,free/reduced,none,0,17,10,51.58,85,97,9.000000

In [88]:
df_exams.sort_values(
    by="race/ethnicity", 
    ascending=True, 
    key=lambda col:col.str.lower() # it's to avoid lower/upper case of string values
    )

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_A,score_B,average score
688,male,81,group A,high school,free/reduced,none,53,58,44,9.77,81,21,51.666667
365,male,100,group A,bachelor's degree,free/reduced,completed,49,58,60,56.25,100,8,55.666667
769,male,17,group A,some college,free/reduced,none,58,60,57,76.55,17,28,58.333333
490,female,48,group A,associate's degree,free/reduced,none,65,85,76,96.02,48,35,75.333333
820,female,67,group A,some high school,standard,completed,85,90,92,19.69,67,58,89.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,male,30,group E,some college,standard,completed,84,83,78,31.75,30,19,81.666667
182,female,25,group E,high school,standard,none,50,50,47,9.10,25,9,49.000000
581,female,22,group E,some high school,standard,none,77,79,80,6.81,22,4,78.666667
755,female,28,group E,associate's degree,standard,none,84,95,92,72.50,28,20,90.333333
458,female,15,group E,bachelor's degree,standard,none,100,100,100,85.94,15,53,100.000000

## 10. Create Index

In [89]:
import random

In [90]:
new_index = np.arange(0, 1000)

In [91]:
random.shuffle(new_index)

In [93]:
df_exams["new_index"] = new_index
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_A,score_B,average score,new_index
458,female,15,group E,bachelor's degree,standard,none,100,100,100,85.94,15,53,100.000000,521
916,male,33,group E,bachelor's degree,standard,completed,100,100,100,38.13,33,49,100.000000,137
962,female,37,group E,associate's degree,standard,none,100,100,100,49.79,37,94,100.000000,571
149,male,78,group E,associate's degree,free/reduced,completed,100,100,93,24.75,78,77,97.666667,209
625,male,6,group D,some college,standard,completed,100,97,99,80.42,6,62,98.666667,360
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,8,group C,some college,free/reduced,none,22,39,33,45.46,8,84,31.333333,625
787,female,41,group B,some college,standard,none,19,38,32,13.83,41,76,29.666667,584
17,female,43,group B,some high school,free/reduced,none,18,32,28,56.24,43,80,26.000000,243
980,female,40,group B,high school,free/reduced,none,8,24,23,22.23,40,94,18.333333,277
59,female,85,group C,some high school,free/reduced,none,0,17,10,51.58,85,97,9.000000,736

### 10.1. Seting the index

In [95]:
df_exams = df_exams.set_index("new_index")
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_A,score_B,average score
new_index,,,,,,,,,,,,,
521,female,15,group E,bachelor's degree,standard,none,100,100,100,85.94,15,53,100.000000
137,male,33,group E,bachelor's degree,standard,completed,100,100,100,38.13,33,49,100.000000
571,female,37,group E,associate's degree,standard,none,100,100,100,49.79,37,94,100.000000
209,male,78,group E,associate's degree,free/reduced,completed,100,100,93,24.75,78,77,97.666667
360,male,6,group D,some college,standard,completed,100,97,99,80.42,6,62,98.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
625,female,8,group C,some college,free/reduced,none,22,39,33,45.46,8,84,31.333333
584,female,41,group B,some college,standard,none,19,38,32,13.83,41,76,29.666667
243,female,43,group B,some high school,free/reduced,none,18,32,28,56.24,43,80,26.000000
277,female,40,group B,high school,free/reduced,none,8,24,23,22.23,40,94,18.333333
736,female,85,group C,some high school,free/reduced,none,0,17,10,51.58,85,97,9.000000

### 10.2. Sorting the index

In [99]:
df_exams = df_exams.sort_index()

In [100]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_A,score_B,average score
new_index,,,,,,,,,,,,,
0,female,5,group B,some college,standard,none,82,85,87,91.17,5,52,84.666667
1,male,47,group B,high school,standard,completed,72,65,68,83.40,47,46,68.333333
2,male,94,group C,associate's degree,free/reduced,none,55,61,54,29.51,94,28,56.666667
3,female,72,group C,some high school,standard,completed,59,54,67,47.25,72,27,60.000000
4,female,81,group E,associate's degree,standard,none,87,94,95,49.29,81,59,92.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,89,group C,associate's degree,standard,completed,67,84,86,93.49,89,15,79.000000
996,female,44,group B,high school,standard,none,62,62,63,55.73,44,76,62.333333
997,female,36,group D,master's degree,free/reduced,completed,61,71,78,48.51,36,15,70.000000
998,female,64,group A,some high school,free/reduced,none,44,45,45,46.55,64,44,44.666667
999,male,64,group C,high school,standard,none,68,60,53,1.13,64,14,60.333333

## 11. Rename Column

In [102]:
df_exams = df_exams.rename(columns={"gender": "Gender"})
df_exams

,Gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_A,score_B,average score
new_index,,,,,,,,,,,,,
0,female,5,group B,some college,standard,none,82,85,87,91.17,5,52,84.666667
1,male,47,group B,high school,standard,completed,72,65,68,83.40,47,46,68.333333
2,male,94,group C,associate's degree,free/reduced,none,55,61,54,29.51,94,28,56.666667
3,female,72,group C,some high school,standard,completed,59,54,67,47.25,72,27,60.000000
4,female,81,group E,associate's degree,standard,none,87,94,95,49.29,81,59,92.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,89,group C,associate's degree,standard,completed,67,84,86,93.49,89,15,79.000000
996,female,44,group B,high school,standard,none,62,62,63,55.73,44,76,62.333333
997,female,36,group D,master's degree,free/reduced,completed,61,71,78,48.51,36,15,70.000000
998,female,64,group A,some high school,free/reduced,none,44,45,45,46.55,64,44,44.666667
999,male,64,group C,high school,standard,none,68,60,53,1.13,64,14,60.333333

In [104]:
columns_rename = {
    "math score": "MS", 
    "reading score": "RS", 
    "writing score": "WS"
    }

df_exams = df_exams.rename(columns=columns_rename)
df_exams

,Gender,test,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS,language score,score_A,score_B,average score
new_index,,,,,,,,,,,,,
0,female,5,group B,some college,standard,none,82,85,87,91.17,5,52,84.666667
1,male,47,group B,high school,standard,completed,72,65,68,83.40,47,46,68.333333
2,male,94,group C,associate's degree,free/reduced,none,55,61,54,29.51,94,28,56.666667
3,female,72,group C,some high school,standard,completed,59,54,67,47.25,72,27,60.000000
4,female,81,group E,associate's degree,standard,none,87,94,95,49.29,81,59,92.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,89,group C,associate's degree,standard,completed,67,84,86,93.49,89,15,79.000000
996,female,44,group B,high school,standard,none,62,62,63,55.73,44,76,62.333333
997,female,36,group D,master's degree,free/reduced,completed,61,71,78,48.51,36,15,70.000000
998,female,64,group A,some high school,free/reduced,none,44,45,45,46.55,64,44,44.666667
999,male,64,group C,high school,standard,none,68,60,53,1.13,64,14,60.333333

In [105]:
df_exams = df_exams.rename(index={0:"A", 1:"B", 2:"C"})
df_exams

,Gender,test,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS,language score,score_A,score_B,average score
new_index,,,,,,,,,,,,,
A,female,5,group B,some college,standard,none,82,85,87,91.17,5,52,84.666667
B,male,47,group B,high school,standard,completed,72,65,68,83.40,47,46,68.333333
C,male,94,group C,associate's degree,free/reduced,none,55,61,54,29.51,94,28,56.666667
3,female,72,group C,some high school,standard,completed,59,54,67,47.25,72,27,60.000000
4,female,81,group E,associate's degree,standard,none,87,94,95,49.29,81,59,92.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,89,group C,associate's degree,standard,completed,67,84,86,93.49,89,15,79.000000
996,female,44,group B,high school,standard,none,62,62,63,55.73,44,76,62.333333
997,female,36,group D,master's degree,free/reduced,completed,61,71,78,48.51,36,15,70.000000
998,female,64,group A,some high school,free/reduced,none,44,45,45,46.55,64,44,44.666667
999,male,64,group C,high school,standard,none,68,60,53,1.13,64,14,60.333333