### 1. Configuration

In [47]:
import pandas as pd
import numpy as np
import random

In [48]:
pd.set_option("display.max_columns", 1000)

In [49]:
df = pd.read_csv("bestsellers with categories.csv")

### 2. Basic Informations

In [50]:
df.dtypes

Name            object
Author          object
User Rating    float64
Reviews          int64
Price            int64
Year             int64
Genre           object
dtype: object

In [51]:
df.shape

(550, 7)

In [52]:
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [53]:
df.describe()

       User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

### 3. Add new column

In [54]:
rating = []

for i in range(0,len(df)):
    rating.append(random.uniform(1,5))

In [55]:
df["Critic Rating"] = rating

In [56]:
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre,Critic Rating
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,3.764440
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,3.157149
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,4.419296
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,3.121436
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,1.997853

### 4. Rearanging the DataFrame

In [57]:
df.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre',
       'Critic Rating'],
      dtype='object')

In [58]:
new_columns = ["Name", "Author", "User Rating", "Critic Rating", "Reviews", "Price", "Year", "Genre"]
df = df[new_columns]

In [59]:
df.head()

,Name,Author,User Rating,Critic Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,3.764440,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,3.157149,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,4.419296,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,3.121436,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,1.997853,7665,12,2019,Non Fiction

### 5. Operations

In [60]:
df["Average Rating"] = (df["User Rating"] + df["Critic Rating"])/2

In [61]:
df = df.round(1)

In [62]:
df.head()

,Name,Author,User Rating,Critic Rating,Reviews,Price,Year,Genre,Average Rating
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,3.8,17350,8,2016,Non Fiction,4.2
1,11/22/63: A Novel,Stephen King,4.6,3.2,2052,22,2011,Fiction,3.9
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,4.4,18979,15,2018,Non Fiction,4.6
3,1984 (Signet Classics),George Orwell,4.7,3.1,21424,6,2017,Fiction,3.9
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,2.0,7665,12,2019,Non Fiction,3.4

In [63]:
df["Genre"].value_counts(normalize=True).round(2)

Genre
Non Fiction    0.56
Fiction        0.44
Name: proportion, dtype: float64

In [67]:
rename = {
    "User Rating": "UR",
    "Critic Rating": "CR",
    "Average Rating": "AR"
}

df = df.rename(columns=rename)

In [68]:
new_order = ["Name", "Author", "Price", "Year", "Genre", "Reviews", "UR", "CR", "AR"]
df = df[new_order]

In [69]:
df.head()

,Name,Author,Price,Year,Genre,Reviews,UR,CR,AR
0,10-Day Green Smoothie Cleanse,JJ Smith,8,2016,Non Fiction,17350,4.7,3.8,4.2
1,11/22/63: A Novel,Stephen King,22,2011,Fiction,2052,4.6,3.2,3.9
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,15,2018,Non Fiction,18979,4.7,4.4,4.6
3,1984 (Signet Classics),George Orwell,6,2017,Fiction,21424,4.7,3.1,3.9
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,12,2019,Non Fiction,7665,4.8,2.0,3.4

### 6. Sorting

In [72]:
df = df.sort_values(by=["UR", "CR"], ascending=False)
df

,Name,Author,Price,Year,Genre,Reviews,UR,CR,AR
521,Unfreedom of the Press,Mark R. Levin,11,2019,Non Fiction,5956,4.9,4.9,4.9
157,Harry Potter and the Sorcerer's Stone: The Ill...,J.K. Rowling,22,2016,Fiction,10052,4.9,4.8,4.8
40,"Brown Bear, Brown Bear, What Do You See?",Bill Martin Jr.,5,2017,Fiction,14344,4.9,4.7,4.8
147,"Goodnight, Goodnight Construction Site (Hardco...",Sherri Duskey Rinker,7,2013,Fiction,7038,4.9,4.6,4.7
303,Strange Planet (Strange Planet Series),Nathan W. Pyle,6,2019,Fiction,9382,4.9,4.6,4.8
...,...,...,...,...,...,...,...,...,...
393,The Goldfinch: A Novel (Pulitzer Prize for Fic...,Donna Tartt,20,2014,Fiction,33844,3.9,2.5,3.2
106,Fifty Shades of Grey: Book One of the Fifty Sh...,E L James,14,2012,Fiction,47265,3.8,2.6,3.2
107,Fifty Shades of Grey: Book One of the Fifty Sh...,E L James,14,2013,Fiction,47265,3.8,1.7,2.7
132,Go Set a Watchman: A Novel,Harper Lee,19,2015,Fiction,14982,3.6,4.4,4.0
353,The Casual Vacancy,J.K. Rowling,12,2012,Fiction,9372,3.3,3.3,3.3